### ISSUE TITLE
ReadMe links broken

### ISSUE THREAD

**Issue by colmbrady** [newsuk/fructose#101]
"We recommend looking at the examples for web and native as there are slight differences."

This line in your ReadMe has broken links.

**Comment by colmbrady** [comment]
Infact, I think most of the links are broken for me.

e.g. https://github.com/newsuk/fructose/blob/master/e2eTests/.fructose/jest-setup.js

**Comment by L0wry** [comment]
@colmbrady big changes to make things easier in 
https://github.com/newsuk/fructose/pull/111

**Comment by L0wry** [comment]
You're all good @colmbrady
