### ISSUE TITLE
"compile-tests" bin points to a file that doesn't exist

### ISSUE THREAD

**Issue by lsjroberts** [newsuk/fructose#136]
In [package.json](https://github.com/newsuk/fructose/blob/master/package.json) you have:

```json
  "bin": {
    "compile-tests": "packages/test-helpers/bin/writeComponentsTests.js",
  }
```

That file does not appear to exist in [packages/test-helpers/bin/](https://github.com/newsuk/fructose/tree/master/packages/test-helpers/bin) and causes an error when trying to run `npm i @times-components/fructose`:

```
npm ERR! enoent ENOENT: no such file or directory, chmod '/my/project/node_modules/@times-components/fructose/packages/test-helpers/bin/writeComponentsTests.js'
```

**Comment by L0wry** [comment]
@lsjroberts good to see you trying out fructose and sorry for the delayed response.
Unfortunately, there have been other priorities and I have only just seen this.

`writeComponentsTests` is a hangover from an old implementation.
it's no longer required and I'll remove it now.

Let me know if you need anything else in using the library!

**Comment by L0wry** [comment]
https://github.com/newsuk/fructose/pull/139

**Comment by lsjroberts** [comment]
> Let me know if you need anything else in using the library!

Cheers @L0wry, will do :)
