### ISSUE TITLE
Use of ID for loading fructose components in app

### ISSUE THREAD

**Issue by kaliabadi** [newsuk/fructose#36]
Perhaps we could add a unique identifier as a property on the components and use that to pull up our components from within the fructose app. 

I believe this is a more defensive method as we are not as reliant on the format of the react native components. 

The down side of this is in the components them selves you will need to add some testing prop. Similar in concept to CSS ID tags.

**Comment by rjanjua** [comment]
you will be pleased to know this was done in #18
