### ISSUE TITLE
Non descriptive errors

### ISSUE THREAD

**Issue by MarkConway94** [newsuk/fructose#53]
The `throw new Error("should be the hobbit!");` is only thrown when the text here eg. "The Hobbit" is different to that of a `if (a !== "The Hobbit") {`
If "The Hobbit" text is different here: `<Text style={styles.title} fructoseID="hobbit">The Hobbit</Text>,`
or here `await driver.waitForVisible('//*[@text="The Hobbit"]', 6000);`
or here `const a = await driver.getText('//*[@text="The Hobbit"]');`
then only a plain Error is shown, see the attached screenshots.
Should errors at these points have better descriptions?

```
withComponent(
  <Text style={styles.title} fructoseID="hobbit">The Hobbit</Text>,
  "basic text",
  fructose => {
    beforeEach(async () => {
      await fructose.loadComponent();
    });

    test("simple test", async () => {
      await driver.waitForVisible('//*[@text="The Hobbit"]', 6000);
      const a = await driver.getText('//*[@text="The Hobbit"]');
      if (a !== "The Hobbit") {
        throw new Error("should be the hobbit!");
      }
    });
  }
);
```
![plain error](https://user-images.githubusercontent.com/9091447/31232905-0edfa3c0-a9e3-11e7-951a-c47cb8888b4f.png)
![descriptive error](https://user-images.githubusercontent.com/9091447/31232903-0ec898b0-a9e3-11e7-8bc1-d762653700fd.png)

**Comment by kaliabadi** [comment]
fixed
