### ISSUE TITLE
logs are very noisy

### ISSUE THREAD

**Issue by rjanjua** [newsuk/fructose#76]
<img width="1189" alt="screen shot 2017-11-30 at 11 24 53" src="https://user-images.githubusercontent.com/7603827/33428544-2dc37d3e-d5c1-11e7-910c-038ea6bb27db.png">

Logs are logging all previous 'loaded components' as well as the currently loaded one. We only want the currently loaded one.

**Comment by L0wry** [comment]
shut the logs up with https://github.com/newsuk/fructose/pull/77
